import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class Print {

	public static final boolean PRINT_CONSTANT_POOL = true;
	public static final String YELLOW_STRING = ConsoleColors.YELLOW + "%s" + ConsoleColors.RESET;
	public static final String SP_5 = " ".repeat(5);
	AttributePrinter attributePrinter = new AttributePrinter();

	void u2(Parser.U2 u2, String title, String titleColor) {
		u2(u2, title, titleColor, false);
	}

	void u2(Parser.U2 u2, String title) {
		u2(u2, title, "", false);
	}

	void u2(Parser.U2 u2, String title, String titleColor, boolean addDecimal) {
		String formatedValue = String.format(" %02X" + (addDecimal ? "(%02d)" : ""), u2.getValue(), u2.getValue());
		System.out.printf("%04X " + titleColor + "%s" + ConsoleColors.RESET + " %s" + YELLOW_STRING + "\n",
				u2.getOffset(), title, formatedValue, u2.getSymbolic());
	}

	void u4(Parser.U4 u4) {
		System.out.printf("%04X %s %02X" + YELLOW_STRING + "\n",
				u4.getOffset(), "Attribute length", u4.getValue(), u4.getSymbolic());
	}

	public void constantPool(List<Parser.ConstantPoolRecord> constants) {
		if (!PRINT_CONSTANT_POOL) {
			return;
		}
		for (int i = 0; i < constants.size(); i++) {
			printRecord(constants, i);
			Parser.ConstantPoolRecord cpr = constants.get(i);
			if (cpr.getRecord().isTwoEntriesTakeUp()) {
				i++;
			}
		}
	}

	void printRecord(List<Parser.ConstantPoolRecord> constants, int idx) {
		Parser.ConstantPoolRecord cpr = constants.get(idx);
		String cpName = cpr.getRecord().name().replaceFirst("^CONSTANT_", "");
		System.out.printf("%04X %4X %19s %s\n", cpr.getOffset(), cpr.getIdx(), cpName, cpr.getAdditional(constants));
	}

	void accessFlags(Parser.U2 u2, Type type) {
		accessFlags(u2, type, "Access flags");
	}

	void accessFlags(Parser.U2 u2, Type type, String title) {
		Map<Integer, String> flagsMap = switch (type) {
			case CLASS -> Map.ofEntries(
					Map.entry(0x0001, "ACC_PUBLIC"),     //   Declared public; may be accessed from outside its package.
					Map.entry(0x0002, "ACC_PRIVATE"),    //   Marked private in source. (Nested)
					Map.entry(0x0004, "ACC_PROTECTED"),  //   Marked protected in source. (Nested)
					Map.entry(0x0008, "ACC_STATIC"),     //   Marked or implicitly static in source. (Nested)
					Map.entry(0x0010, "ACC_FINAL"),      //   Declared final; no subclasses allowed.
					Map.entry(0x0020, "ACC_SUPER"),      //   Treat superclass methods specially when invoked by the invokespecial instruction.
					Map.entry(0x0200, "ACC_INTERFACE"),  //   Is an interface, not a class.
					Map.entry(0x0400, "ACC_ABSTRACT"),   //   Declared abstract; must not be instantiated.
					Map.entry(0x1000, "ACC_SYNTHETIC"),  //   Declared synthetic; not present in the source code.
					Map.entry(0x2000, "ACC_ANNOTATION"), //   Declared as an annotation type.
					Map.entry(0x4000, "ACC_ENUM"),       //   Declared as an enum type.
					Map.entry(0x8000, "ACC_MODULE")      //   Is a module, not a class or interface.*/
			);
			case FIELD -> Map.of(
					0x0001, "ACC_PUBLIC",    // Declared public; may be accessed from outside its package.
					0x0002, "ACC_PRIVATE",   // Declared private; accessible only within the defining class and other classes belonging to the same nest (§5.4.4).
					0x0004, "ACC_PROTECTED", // Declared protected; may be accessed within subclasses.
					0x0008, "ACC_STATIC",    // Declared static.
					0x0010, "ACC_FINAL",     // Declared final; never directly assigned to after object construction (JLS §17.5).
					0x0040, "ACC_VOLATILE",  // Declared volatile; cannot be cached.
					0x0080, "ACC_TRANSIENT", // Declared transient; not written or read by a persistent object manager.
					0x1000, "ACC_SYNTHETIC", // Declared synthetic; not present in the source code.
					0x4000, "ACC_ENUM"       // Declared as an element of an enum.
			);
			case METHOD -> Map.ofEntries(
					Map.entry(0x0001, "ACC_PUBLIC"),       //Declared public; may be accessed from outside its package.
					Map.entry(0x0002, "ACC_PRIVATE"),      //Declared private; accessible only within the defining class and other classes belonging to the same nest (§5.4.4).
					Map.entry(0x0004, "ACC_PROTECTED"),    //Declared protected; may be accessed within subclasses.
					Map.entry(0x0008, "ACC_STATIC"),       //Declared static.
					Map.entry(0x0010, "ACC_FINAL"),        //Declared final; must not be overridden (§5.4.5).
					Map.entry(0x0020, "ACC_SYNCHRONIZED"), //Declared synchronized; invocation is wrapped by a monitor use.
					Map.entry(0x0040, "ACC_BRIDGE"),       //A bridge method, generated by the compiler.
					Map.entry(0x0080, "ACC_VARARGS"),      //Declared with variable number of arguments.
					Map.entry(0x0100, "ACC_NATIVE"),       //Declared native; implemented in a language other than the Java programming language.
					Map.entry(0x0400, "ACC_ABSTRACT"),     //Declared abstract; no implementation is provided.
					Map.entry(0x0800, "ACC_STRICT"),       //Declared strictfp; floating-point mode is FP-strict.
					Map.entry(0x1000, "ACC_SYNTHETIC")     //Declared synthetic; not present in the source code.
			);
			default -> new HashMap<>();
		};

		String string = getAccessFlags(u2.getValue(), flagsMap);
		System.out.printf("%04X %s 0x%02X" + YELLOW_STRING + "\n", u2.getOffset(), title, u2.getValue(), string);
	}

	private String getAccessFlags(int value, Map<Integer, String> flagsMap) {
		StringBuilder res = new StringBuilder();
		for (int bit = 1; bit < 0x100000; bit <<= 1) {
			String flag = flagsMap.get(value & bit);
			if (flag != null && !flag.isEmpty()) {
				res.append(" ").append(flag.replaceFirst("ACC_", ""));
			}
		}
		return res.toString().toLowerCase();
	}

	public void attributes(Map<String, Attribute> attributes) {
		for (Map.Entry<String, Attribute> entry : attributes.entrySet()) {
			Attribute attr = entry.getValue();
			attr.print(attributePrinter);
		}
	}

	public interface Printable {
		void print(AttributePrinter printer);
	}

	public class AttributePrinter {
		void print(Attribute attr) {
			u2(attr.getNameIndex(), "Attribute name index");
			u4(attr.getLength());
		}

		void print(Attribute.SourceFileAttribute attr) {
			u2(attr.getSourceFileIndex(), "Attribute source file index");
		}

		void print(Attribute.NestMembersAttribute attr) {
			Parser.U2[] classes = attr.getClasses();
			u2(attr.getNumberOfClasses(), "Attribute number of classes");
			for (Parser.U2 aClass : classes) {
				u2(aClass, SP_5 + "Nest");
			}
		}

		void print(Attribute.InnerClassesAttribute attr) {
			u2(attr.getNumberOf(), "Attribute number of inner classes");
			for (Attribute.InnerClass innerClass : attr.getInnerClasses()) {
				innerClass.print(this);
			}
		}


		void print(Attribute.BootstrapMethodsAttribute attr) {
			u2(attr.getNumberOf(), "Attribute number of bootstrap methods");
			for (Attribute.BootstrapMethod bootstrapMethod : attr.getBootstrapMethods()) {
				bootstrapMethod.print(this);
			}
		}

		void print(Attribute.BootstrapMethod bootstrapMethod) {
			var formatedIndex = String.format("%4X ", bootstrapMethod.index());
			u2(bootstrapMethod.bootstrapMethodRef(), formatedIndex + "Bootstrap method");
			for (Parser.U2 u2 : bootstrapMethod.bootstrapArguments()) {
				u2(u2, SP_5 + "Argument");
			}
		}

		public void print(Attribute.InnerClass innerClass) {
			u2(innerClass.innerClassInfoIndex(), SP_5 + "Inner class");
			u2(innerClass.outerClassInfoIndex(), SP_5 + "Outer class");
			u2(innerClass.innerNameIndex(), SP_5 + "Inner name index");
			accessFlags(innerClass.innerClassAccessFlags(), Type.CLASS, SP_5 + "Inner class access flags");
		}
	}
}
